============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
/var/spool/slurm/slurmd/job9873269/slurm_script: line 13: cd: AutoregressiveNeuralOperators: No such file or directory
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: tpharmsen (tpharmsen-tue). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.19.1
wandb: Run data is saved locally in /gpfs/home5/tharmsen/AutoregressiveNeuralOperators/wandb/run-20250211_204347-fmtd9mlf
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run UNet_mod1_hpc_01DS1_1
wandb: ‚≠êÔ∏è View project at https://wandb.ai/tpharmsen-tue/BubbleML_DS_PF
wandb: üöÄ View run at https://wandb.ai/tpharmsen-tue/BubbleML_DS_PF/runs/fmtd9mlf
dataloader ready
loading UNet_mod1
Amount of parameters in model: 90535948
UNet_mod1 initialized
start training
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/wandb/sdk/lib/exit_hooks.py", line 41, in exc_handler
    def exc_handler(

  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/torch/utils/data/_utils/signal_handling.py", line 73, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1763278) is killed by signal: Killed. 

Original exception was:
Traceback (most recent call last):
  File "/gpfs/home5/tharmsen/AutoregressiveNeuralOperators/src/train.py", line 20, in <module>
    trainer.train()
  File "/gpfs/home5/tharmsen/AutoregressiveNeuralOperators/src/trainers/PFTB.py", line 475, in train
    train_losses = self.train_one_epoch()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home5/tharmsen/AutoregressiveNeuralOperators/src/trainers/PFTB.py", line 229, in train_one_epoch
    for idx, (coords, temp, vel, phase, temp_label, vel_label, phase_label) in enumerate(self.train_loader):
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1448, in _next_data
    idx, data = self._get_data()
                ^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1412, in _get_data
    success, data = self._try_get_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1243, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
         ^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/multiprocessing/connection.py", line 519, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tharmsen/.conda/envs/grad312/lib/python3.12/multiprocessing/connection.py", line 647, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
[1;34mwandb[0m: üöÄ View run [33mUNet_mod1_hpc_01DS1_1[0m at: [34mhttps://wandb.ai/tpharmsen-tue/BubbleML_DS_PF/runs/fmtd9mlf[0m
[1;34mwandb[0m: Find logs at: [1;35mwandb/run-20250211_204347-fmtd9mlf/logs[0m
slurmstepd: error: Detected 1 oom_kill event in StepId=9873269.batch. Some of the step tasks have been OOM Killed.

JOB STATISTICS
==============
Job ID: 9873269
Cluster: snellius
User/Group: tharmsen/tharmsen
State: OUT_OF_MEMORY (exit code 0)
Nodes: 1
Cores per node: 32
CPU Utilized: 00:16:16
CPU Efficiency: 7.26% of 03:44:00 core-walltime
Job Wall-clock time: 00:07:00
Memory Utilized: 97.61 GB
Memory Efficiency: 54.23% of 180.00 GB
